[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/characters"
  to = "/.netlify/functions/server/api/characters"

[[redirects]]
  from = "/characters/schema/"
  to = "/.netlify/functions/server/api/characters/schema" 

[[redirects]]
  from = '/characters/:id'
  to = "/.netlify/functions/server/api/characters/:id"